update mongo object model
alercebroker/db-plugins pull request #35
Opened 2022-08-04 14:06 UTC by AlxEnashi

with magstats, features and probabilities

2022-08-04 14:46 UTC, pcastelln approved these changes

2022-12-14 15:06 UTC, dirodriguezm requested changes

2022-12-14 15:06 UTC, dirodriguezm commented on db_plugins/db/mongo/query.py
> +    def bulk_update(self, instances: list, attrs: list, filter_fields: list = None):
Dejar solamente dos argumentos, uno para los documentos / filtros que se van a actualizar y la lista de dict que contiene los atributos que se van a reemplazar

2022-12-14 15:10 UTC, dirodriguezm requested changes
Actualizar version del setup

2022-12-14 19:34 UTC, dirodriguezm approved these changes

2022-12-14 19:46 UTC, merged